In [1]:
import numpy as np

a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a[0],a[1],a[2])

1 2 3


In [7]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [8]:
print(b[0,0],b[0,1],b[1,0])

1 2 4


In [10]:
a = np.zeros((2,2))
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [11]:
b = np.ones((1,2))
print(b)

[[ 1.  1.]]


In [12]:
c = np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [13]:
d = np.eye(2) #identity matrix
print(d)

[[ 1.  0.]
 [ 0.  1.]]


In [15]:
e = np.random.random((2,2))
print(e)

[[ 0.95169671  0.58652433]
 [ 0.55018416  0.7206081 ]]


In [22]:
#indexing
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
#1st two rows and collumns 1 and 2
b = a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [23]:
#references the same object
print(a[0,1])
b[0,0] = 99
print(a[0,1])

2
99


In [31]:
# more indexing 
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row1 = a[1,:]
row2 = a[1:2,:]
print(row1,row1.shape)
print(row2,row2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [34]:
col1 = a[:,1]
col2 = a[:,1:2]
print(col1,col1.shape)
print(col2,col2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [36]:
a = np.array([[1,2], [3, 4], [5, 6]])
a.shape

(3, 2)

In [37]:
#integer array indexing allows you to
#construct arbitrary arrays using the data from another array.
print(a[[0,1,2],[0,1,0]])
#accesses indexes (0,0) (1,1) (2,0)
#equivelent to
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]


In [39]:
#can reuse elements
print(a[[0,0],[1,1]]) # (0,1), (0,1)

[2 2]


In [41]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

#array of indexes 
b = np.array([0,2,0,1])

#arange(4) = [0,1,2,3]
print(a[np.arange(4),b])

[ 1  6  7 11]


In [42]:
#change one elem  from each row
a[np.arange(4),b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [43]:
#boolean indexing
a = np.array([[1,2], [3, 4], [5, 6]])

bool_indx = (a > 2)

print(bool_indx)

[[False False]
 [ True  True]
 [ True  True]]


In [44]:
print(a[bool_indx])

[3 4 5 6]


In [45]:
print(a[(a > 2)])

[3 4 5 6]


In [46]:
#datatypes - all elems of the array are of the same type
# type is infered 

x = np.array([1,2])
print(x.dtype)


int64


In [47]:
x = np.array([1.0,2.0])
print(x.dtype)

float64


In [48]:
#array math
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

#element wise sum
print(x+y)
print(np.add(x,y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


In [49]:
#element wise difference
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [50]:
#element wise prod
x*y
np.multiply(x,y)
#element wise division
x/y
np.divide(x,y)

#element wise sqrt
print(np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [52]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

#inner prod of vectors
print(v.dot(w))
#also exists as function
print(np.dot(v,w))

219
219


In [53]:
#matrix mul
print(x.dot(y))

[[19 22]
 [43 50]]


In [55]:
#sum over arrays
x = np.array([[1,2],[3,4]])

print(np.sum(x)) #sum of all elems

10


In [56]:
print(np.sum(x,axis=0)) #sum of each collumn

[4 6]


In [58]:
print(np.sum(x,axis=1)) #sum of each row

[3 7]


In [66]:
x = np.array([[1,2],[3,4]])
print(x)

print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [67]:
#transpose of rank1 array does nothing
v = np.array([1,2,3])
print(v)
print(v.T)

[1 2 3]
[1 2 3]


In [68]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [74]:
#same as before but more efficient
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [75]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [76]:
#BUT THIS WORKS even if different shapes. Done automatically
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [78]:
#Functions that support broadcasting are known as universal functions

v = np.array([1,2,3])
w = np.array([4,5])
np.reshape(v,(3,1))*w #outerprod

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [79]:
#add vector to each row
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

[[2 4 6]
 [5 7 9]]


In [80]:
#add vector to each collumn
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [81]:
#multiply matrix by constant
print(x*2)

[[ 2  4  6]
 [ 8 10 12]]
